pipeline {
    agent any

    stages {
        stage ('GetProject') {
            steps {
                //git branch:'master', url:'https://github.com/JamesSheridanCode/PackageSpringBoot.git'
                git 'https://github.com/JamesSheridanCode/Springboot3.git'
            }
        }
        stage ('build') {
            steps {
                //sh 'mvn clean'
                            //sh 'mvn clean:clean'
                            //sh 'mvn dependency:copy-dependencies'
                            //sh 'mvn compiler:compile'
                             sh 'java -version'
                             sh 'mvn clean compile'
                             sh "mvn clean:clean"

                             sh "mvn dependency:copy-dependencies"

                             sh "mvn compiler:compile"
            }
        }
        stage ('Package') {
            steps {
                sh 'mvn package'
            }
        }
    }
        post {
            success {

                archiveArtifacts allowEmptyArchive: true,
                    artifacts: '**/packagetest*.war'
            }
        }

}