pipeline {
    agent any


    stages {

        stage('Checkout') {
                            steps {
                                // This checkout clones the whole repository into Jenkins workspace
                                checkout scm
                            }
                        }
        stage ('GetProject') {
            steps {
                //git branch:'master', url:'https://github.com/JamesSheridanCode/PackageSpringBoot.git'
                dir('packagetest'){
                git branch:'master', url:'https://github.com/JamesSheridanCode/Springboot4.git'
                }
            }
        }
        stage ('build') {
            steps {
                //sh 'mvn clean'
                            //sh 'mvn clean:clean'
                            //sh 'mvn dependency:copy-dependencies'
                            //sh 'mvn compiler:compile'
                            dir('packagetest'){
                             sh 'java -version'
                             sh 'mvn clean compile'
                             sh "mvn clean:clean"

                             sh "mvn dependency:copy-dependencies"

                             sh "mvn compiler:compile"
                             }
            }
        }
        stage ('Package') {
            steps {
                dir('packagetest'){
                sh 'mvn package'
                }
            }
        }

        stage ('Archive') {
                    steps {

                        archiveArtifacts allowEmptyArchive: true,
                            artifacts: '**/packagetest*.war'
                    }
        }

        stage ('Deploy'){
            steps {
                    sh 'sudo docker build -f Dockerfile -t myapp . '
                   }
        }
    }


}